version: 1.0.0-rc2-{build}
build_script:
- ps: .\build.ps1 $env:APPVEYOR_BUILD_NUMBER
artifacts:
- path: .\artifacts\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: fKfbMt3f7QbhpK3pZBY4x64qsOEs3KG2tWZlZOBnEo4wDA54KOch2hTZKPFybVTn